spring.application.name=bhagavadgita-api
spring.datasource.url=jdbc:postgresql://localhost:5432/bhagavadgita
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true